#!/bin/python3

import math
import os
import random
import re
import sys



if __name__ == '__main__':
    n = int(input())
    for i in range(1,11):
        if(1 <= i <= 10):
            result = n*i
            print(n,"x",i,"=",result)
